import { useCallback, useEffect, useRef, useState } from "react";
import { CanvasTexture, LinearFilter, RGBAFormat, SRGBColorSpace } from "three";
import { scrollState } from "./scrollStore";

export type RiderFrameStatus = "loading" | "ready" | "error";

export interface RiderFrameSequenceState {
  status: RiderFrameStatus;
  texture: CanvasTexture | null;
  aspect: number;
  frameCount: number;
}

const ASSET_BASE = `${import.meta.env.BASE_URL}assets/avatar/rider-frames`;
const MANIFEST_URL = `${ASSET_BASE}/manifest.json`;
const MOBILE_BREAKPOINT_PX = 700;

interface Manifest {
  count: number;
  fps: number;
  variants: Record<string, { width: number; height: number }>;
}

function loadImage(src: string): Promise<HTMLImageElement> {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.decoding = "async";
    img.onload = () => resolve(img);
    img.onerror = () => reject(new Error(`failed to load ${src}`));
    img.src = src;
  });
}

/**
 * Loads the pre-rendered rider frame sequence (public/assets/avatar/
 * rider-frames/, generated by `npm run frames:extract` ->
 * scripts/extract-rider-frames.mjs) and exposes a single, reused
 * THREE.CanvasTexture. Call the returned `updateFrame(index)` to redraw it
 * in place -- this is the primary scrub mechanism, replacing WebM
 * currentTime-seeking.
 *
 * Why: this project's rider clip encodes alpha via a WebM side-channel that
 * ffmpeg cannot decode (see the extraction script for the full story), and
 * separately, scroll-driven VP9 seeking has real decoder latency that no
 * amount of seek-throttling fully hides -- confirmed by testing both. A
 * preloaded image swapped onto a canvas has none of that latency: it's a
 * synchronous draw, not a seek-and-wait.
 *
 * Never creates a new Texture/canvas/material/mesh while scrubbing, and
 * never triggers a React re-render for a frame change -- `updateFrame` is a
 * stable, memoized function that only touches refs and canvas/texture
 * internals; loaded images and the "currently drawn" index live in refs,
 * not state. `status`/`texture`/`aspect`/`frameCount` only change once,
 * when the sequence first becomes usable.
 */
export function useRiderFrameSequence(): RiderFrameSequenceState & {
  updateFrame: (index: number) => void;
} {
  const [state, setState] = useState<RiderFrameSequenceState>({
    status: "loading",
    texture: null,
    aspect: 9 / 16,
    frameCount: 0,
  });

  const framesRef = useRef<(HTMLImageElement | null)[]>([]);
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const ctxRef = useRef<CanvasRenderingContext2D | null>(null);
  const textureRef = useRef<CanvasTexture | null>(null);
  const lastDrawnIndexRef = useRef(-1);
  const lastRequestedIndexRef = useRef(0);

  const drawIndex = useCallback((requestedIndex: number) => {
    const frames = framesRef.current;
    const ctx = ctxRef.current;
    const canvas = canvasRef.current;
    const texture = textureRef.current;
    if (!ctx || !canvas || !texture || frames.length === 0) return;

    const clamped = Math.max(0, Math.min(frames.length - 1, requestedIndex));
    let resolvedIndex = clamped;
    let img = frames[clamped];
    if (!img) {
      // Progressive loading may not have reached this exact frame yet --
      // fall back to the nearest already-loaded neighbour so the rider
      // never shows a blank/broken frame while it catches up.
      for (let d = 1; d < frames.length && !img; d++) {
        if (frames[clamped - d]) {
          resolvedIndex = clamped - d;
          img = frames[clamped - d];
        } else if (frames[clamped + d]) {
          resolvedIndex = clamped + d;
          img = frames[clamped + d];
        }
      }
    }
    if (!img || resolvedIndex === lastDrawnIndexRef.current) return;

    ctx.clearRect(0, 0, canvas.width, canvas.height);
    ctx.drawImage(img, 0, 0, canvas.width, canvas.height);
    texture.needsUpdate = true;
    lastDrawnIndexRef.current = resolvedIndex;
  }, []);

  const updateFrame = useCallback(
    (index: number) => {
      lastRequestedIndexRef.current = index;
      drawIndex(index);
    },
    [drawIndex]
  );

  useEffect(() => {
    let cancelled = false;

    async function init() {
      let manifest: Manifest;
      try {
        const res = await fetch(MANIFEST_URL);
        if (!res.ok) throw new Error(`manifest request failed: ${res.status}`);
        manifest = await res.json();
      } catch {
        if (!cancelled) setState((s) => ({ ...s, status: "error" }));
        return;
      }
      if (cancelled) return;

      const isMobile = window.innerWidth < MOBILE_BREAKPOINT_PX;
      const variantName = isMobile && manifest.variants.mobile ? "mobile" : "desktop";
      const variant = manifest.variants[variantName] ?? manifest.variants.desktop;
      if (!variant || !manifest.count) {
        setState((s) => ({ ...s, status: "error" }));
        return;
      }

      const frameUrl = (i: number) =>
        `${ASSET_BASE}/${variantName}/frame-${String(i + 1).padStart(4, "0")}.webp`;

      framesRef.current = new Array(manifest.count).fill(null);

      const canvas = document.createElement("canvas");
      canvas.width = variant.width;
      canvas.height = variant.height;
      const ctx = canvas.getContext("2d", { alpha: true });
      if (!ctx) {
        setState((s) => ({ ...s, status: "error" }));
        return;
      }
      canvasRef.current = canvas;
      ctxRef.current = ctx;

      const texture = new CanvasTexture(canvas);
      texture.colorSpace = SRGBColorSpace;
      texture.format = RGBAFormat;
      texture.minFilter = LinearFilter;
      texture.magFilter = LinearFilter;
      texture.generateMipmaps = false;
      textureRef.current = texture;

      // Load the frame nearest wherever the user has already scrolled to
      // (usually 0, but this covers landing mid-intro) before going
      // "ready", so the first paint is exact -- never a flash or a visible
      // catch-up glide once the sequence takes over from the placeholder.
      const initialIndex = Math.round(
        Math.max(0, Math.min(1, scrollState.introProgress)) * (manifest.count - 1)
      );
      try {
        const firstImg = await loadImage(frameUrl(initialIndex));
        if (cancelled) return;
        framesRef.current[initialIndex] = firstImg;
      } catch {
        if (!cancelled) setState((s) => ({ ...s, status: "error" }));
        return;
      }
      if (cancelled) return;

      lastRequestedIndexRef.current = initialIndex;
      drawIndex(initialIndex);

      setState({
        status: "ready",
        texture,
        aspect: variant.width / variant.height,
        frameCount: manifest.count,
      });

      // Progressive background preload: nearest-to-current-scroll-position
      // first, with limited concurrency (lower on mobile) so it never
      // competes hard with anything else happening on the page.
      const remaining = new Set<number>();
      for (let i = 0; i < manifest.count; i++) {
        if (i !== initialIndex) remaining.add(i);
      }

      function pickNext(): number | null {
        const target = lastRequestedIndexRef.current;
        let best: number | null = null;
        let bestDist = Infinity;
        for (const i of remaining) {
          const d = Math.abs(i - target);
          if (d < bestDist) {
            bestDist = d;
            best = i;
          }
        }
        return best;
      }

      function loadNext() {
        if (cancelled) return;
        const idx = pickNext();
        if (idx === null) return;
        remaining.delete(idx);
        loadImage(frameUrl(idx))
          .then((img) => {
            if (cancelled) return;
            framesRef.current[idx] = img;
            // If this is exactly the frame currently being displayed (the
            // user settled here before it had loaded), upgrade immediately
            // instead of waiting for the next scroll tick.
            if (idx === lastRequestedIndexRef.current) drawIndex(idx);
            loadNext();
          })
          .catch(() => {
            if (!cancelled) loadNext();
          });
      }

      const concurrency = isMobile ? 3 : 6;
      for (let c = 0; c < concurrency; c++) loadNext();
    }

    init();

    return () => {
      cancelled = true;
      textureRef.current?.dispose();
      textureRef.current = null;
      framesRef.current = [];
      canvasRef.current = null;
      ctxRef.current = null;
    };
  }, [drawIndex]);

  return { ...state, updateFrame };
}
